### ISSUE TITLE
Chinese characters get merged into one line

### ISSUE THREAD

**Issue by RangerMauve** [slang800/tidy-markdown#10] opened 2015-06-03 18:51 UTC
When beautifying documents written in Chinese, things that were originally on two lines all get merged into one. Could it just be that the unicode isn't being respected?

I'm using this via [atom-beautify](https://atom.io/packages/atom-beautify)

**Comment by RangerMauve** [comment] 2015-06-03 18:58
For example, given the following string:
``` markdown
盖茨很可爱

* 猫尾巴

* 猫的眼睛

我喜欢所有的猫
```

Would turn into the following jumble:

``` markdown
盖茨很可爱 * 猫尾巴 * 猫的眼睛 我喜欢所有的猫
```

As you can see, it even ignores the bullet list definition and concatenates everything on one line

**Comment by slang800** [comment] 2015-06-03 19:34
I'm having trouble reproducing this:

![screenshot from 2015-06-03 15 30 27](https://cloud.githubusercontent.com/assets/1049204/7969538/8573242e-0a05-11e5-9260-ce1d413f2328.png)

It's probably an error with atom, or atom-beautify... especially since when I paste that text into atom, it doesn't even show up:

![screenshot from 2015-06-03 15 33 54](https://cloud.githubusercontent.com/assets/1049204/7969602/f6ccc2a6-0a05-11e5-9a75-450f5f6123c4.png)

**Comment by RangerMauve** [comment] 2015-06-03 19:44
Hmm, good point. I noticed that I wasn't getting syntax highlighting when I was doing that. I'll look into it some more.

**Comment by slang800** [comment] 2015-06-03 19:45
Sounds good - I'mma close this for now, feel free to comment if you find out it is an error in tidy-markdown.

**Closed by slang800** 2015-06-03 19:45 UTC

**Comment by RangerMauve** [comment] 2015-06-03 19:47
Yeah, this is definitely an issue with atom. I've managed to find what causes it and quick fix. I was duplicating an HTML file and renaming the extension to `.md` However when it was opened the language was still set to HTML. Then it seems that even though I was writing markdown, atom-beautify was running the HTML beautifier on the contents. Fixing was as simple as just closing and opening the tab with the file.

Thanks for the help!
